version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd ui
      - npm install
      - cd ..
      - cd dynamo-read
      - npm install
      - cd ..
      - cd dynamo-upload
      - npm install
      - cd ..
  build:
    commands:
      - echo "Building and zipping..."
      - cd ui
      - npm run build
      - cd ..
      - cd dynamo-read
      - zip -r9 dynamoRead.zip .
      - cd ..
      - cd dynamo-upload
      - zip -r9 dynamoUpload.zip .
      - cd ..

  post_build:
    commands:
      - echo "Uploading to lambda..."
      - aws lambda update-function-code --function-name liveScoreGetData --zip-file fileb://dynamo-read/dynamoRead.zip
      - aws lambda update-function-code --function-name liveScorePostData --zip-file fileb://dynamo-upload/dynamoUpload.zip

artifacts:
  files:
    - "**/**"
  discard-paths: no
  base-directory: ui/build
