version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd ui
      - npm install
      - cd ..
  build:
    commands:
      - echo "Building..."
      - cd ui
      - npm run build

  post_build:
    commands:
      # - echo "Uploading to lambda..."
      # - aws lambda update-function-code --function-name s3Upload --zip-file fileb://s3Upload/s3Upload.zip
      # - aws lambda update-function-code --function-name s3ApiGateway --zip-file fileb://dynamoDb/dynamoDb.zip

artifacts:
  files:
    - "**/**"
  discard-paths: no
  base-directory: ui/build
